try{
    console.log(aaaaaaa)
}
catch(error)
{
    console.log(error.name)
}

console.log("bbb")